stellar:
  homepage: 'https://peterliu.github.io'
  repo: 'https://github.com/peter.liu/hexo_blog'


# sidebar:
#   menu:
#     post: '[btn.blog](/)'
#     wiki: '[btn.wiki](/wiki/)'
#     notes: '[笔记](/notes/)'
#     more: '[更多](/more/)'

sidebar:
  menu:
    post: '[btn.blog](/)'
    about: '[关于](/about/)'

  widgets:
    welcome:
      layout: markdown
      title: 欢迎光临我的博客
      content: | # support markdown
        　


        

comments:
  service: beaudar
  beaudar:
    repo: peterliu/blog-comments

# style:
#   darkmode: auto # auto / always / false
#   theme:
#     light: '#f0f0f0' # '#f8f8f8'
#     dark: '#313438'

    

